# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: Kankoda Design System
description: >-
  This is the shared design system for the Kankoda company. 

url: https://design.kankoda.com
email: info@keyboardkit.com

copyright_year: 2025-2026
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: keyboardkit.bsky.social
github_username: KeyboardKit
mastodon_username: keyboardkit@techhub.social
twitter_username: keyboardkitsdk

assets: /assets/

urls:
  email:  mailto:info@kankoda.com
  rss:    https://design.kankoda.com/feed.xml

  blog:   /blog

  appstore:   https://apps.apple.com/us/developer/kankoda-sweden-ab/id516398918
  bluesky:    https://bsky.app/profile/kankoda.bsky.social
  github:     https://github.com/kankoda
  gumroad:    https://kankoda.gumroad.com
  mastodon:   https://mastodon.social/@kankoda
  newsletter: https://kankoda.gumroad.com/subscribe
  twitter:    https://twitter.com/kankodahq

# google-analytics:
#   measurement-id: G-XJ0HPZDSM3

header:
  logo: /assets/logo/header.png
  pages:
    - pages/home.md

footer:
  # Sections with links defined as "Title | url" strings.
  sections:
    - title: Site
      links:
        - Home | /
    - title: SDK
      links:
        - Home | /
    - title: News & Press
      links:
        - Home | /
    - title: Code
      links:
        - Home | /
    - title: Contact
      links:
        - Home | /

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: [".well-known"]

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: page
      image: /assets/headers/kankoda.jpg
  -
    scope:
      path: "pages/blog.md"
    values:
      image: /assets/headers/blog.jpg
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - _docs/